In [1]:
import numpy as np
from pso import *
import networkx as nx
import math

In [2]:
def booth(x):
    """Booth's objective function.

    Only takes two dimensions and has a global minimum of `0` at
    :code:`f([1,3])`. Its domain is bounded between :code:`[-10, 10]`

    Parameters
    ----------
    x : numpy.ndarray
        set of inputs of shape :code:`(n_particles, dimensions)`

    Returns
    -------
    numpy.ndarray
        computed cost of size :code:`(n_particles, )`

    Raises
    ------
    IndexError
        When the input dimensions is greater than what the function
        allows
    ValueError
        When the input is out of bounds with respect to the function
        domain
    """
    if not x.shape[1] == 2:
        raise IndexError("Booth function only takes two-dimensional input.")
    if not np.logical_and(x >= -10, x <= 10).all():
        raise ValueError("Input for Booth function must be within [-10, 10].")

    x_ = x[:, 0]
    y_ = x[:, 1]
    j = (x_ + 2 * y_ - 7) ** 2.0 + (2 * x_ + y_ - 5) ** 2.0

    return j

In [3]:
def easom(x):
    """Easom objective function.

    Only takes two dimensions and has a global minimum of
    `-1` at :code:`f([pi, pi])`.
    Its coordinates are bounded within :code:`[-100,100]`.

    Best visualized in the domain of :code:`[-5, 5]` and a range of :code:`[-1, 0.2]`.

    Parameters
    ----------
    x : numpy.ndarray
        set of inputs of shape :code:`(n_particles, dimensions)`

    Returns
    -------
    numpy.ndarray
        computed cost of size :code:`(n_particles, )`

    Raises
    ------
    IndexError
        When the input dimensions is greater than what the function
        allows
    ValueError
        When the input is out of bounds with respect to the function
        domain
    """
    if not x.shape[1] == 2:
        raise IndexError("Easom function only takes two-dimensional input.")
    if not np.logical_and(x >= -100, x <= 100).all():
        raise ValueError(
            "Input for Easom function must be within [-100, 100]."
        )

    x_ = x[:, 0]
    y_ = x[:, 1]

    j = (
        -1
        * np.cos(x_)
        * np.cos(y_)
        * np.exp(-1 * ((x_ - np.pi) ** 2 + (y_ - np.pi) ** 2))
    )

    return j

In [10]:
grid_mat = nx.ring_of_cliques(2,4)
adj_matrix = nx.adjacency_matrix(grid_mat).todense()

In [15]:
run(easom, adj_matrix, epochs=10,
    lb=[-100, -100], ub=[100, 100],
    c0=0.85, c1=1, c2=2, c3=0, n=adj_matrix.shape[0])

0
1
2
3
4
5
6
7
8
9


(array([[ 14.00097526,  -5.23048832],
        [-53.86343931,  37.16685069],
        [-76.90752995,  57.08163002],
        [ 86.07874366,  47.52508902],
        [ 96.75147427,  48.37880807],
        [ 77.67543377,  31.42144536],
        [ 73.84751983,  33.22275012],
        [  5.74669044,  25.78395525]]),
 array([-1.48752494e-083,  0.00000000e+000, -0.00000000e+000,
        -0.00000000e+000, -0.00000000e+000,  0.00000000e+000,
         0.00000000e+000, -1.71727685e-226]),
 array([14.00097526, -5.23048832]),
 -1.487524942912373e-83)